use_frameworks!

platform :ios, '9.0'

install! 'cocoapods', :deterministic_uuids => false

target 'KaMPStarteriOS' do
  pod 'Firebase/Core'
  pod 'Firebase/Crashlytics'
#  pod 'Fabric'
#  pod 'Crashlytics'
    pod 'shared', :path => '../shared/'
end
